language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install Flask-API
  - pip install flask-jwt-extended
  - pip install cerberus
  - pip install coveralls
  - pip install codeclimate-test-reporter
  - pip install codecov
# command to run tests
script:
  - pytest 
after_success:
 - coveralls
 - codeclimate-test-reporter
 - codecov
  
  